// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fluffy-bunny/sarulabsdi/internal/contracts/something (interfaces: ISomething,ISomething2,ISomething3)

// Package something is a generated GoMock package.
package something

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockISomething is a mock of ISomething interface.
type MockISomething struct {
	ctrl     *gomock.Controller
	recorder *MockISomethingMockRecorder
}

// MockISomethingMockRecorder is the mock recorder for MockISomething.
type MockISomethingMockRecorder struct {
	mock *MockISomething
}

// NewMockISomething creates a new mock instance.
func NewMockISomething(ctrl *gomock.Controller) *MockISomething {
	mock := &MockISomething{ctrl: ctrl}
	mock.recorder = &MockISomethingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISomething) EXPECT() *MockISomethingMockRecorder {
	return m.recorder
}

// GetName mocks base method.
func (m *MockISomething) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockISomethingMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockISomething)(nil).GetName))
}

// MockISomething2 is a mock of ISomething2 interface.
type MockISomething2 struct {
	ctrl     *gomock.Controller
	recorder *MockISomething2MockRecorder
}

// MockISomething2MockRecorder is the mock recorder for MockISomething2.
type MockISomething2MockRecorder struct {
	mock *MockISomething2
}

// NewMockISomething2 creates a new mock instance.
func NewMockISomething2(ctrl *gomock.Controller) *MockISomething2 {
	mock := &MockISomething2{ctrl: ctrl}
	mock.recorder = &MockISomething2MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISomething2) EXPECT() *MockISomething2MockRecorder {
	return m.recorder
}

// GetName mocks base method.
func (m *MockISomething2) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockISomething2MockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockISomething2)(nil).GetName))
}

// MockISomething3 is a mock of ISomething3 interface.
type MockISomething3 struct {
	ctrl     *gomock.Controller
	recorder *MockISomething3MockRecorder
}

// MockISomething3MockRecorder is the mock recorder for MockISomething3.
type MockISomething3MockRecorder struct {
	mock *MockISomething3
}

// NewMockISomething3 creates a new mock instance.
func NewMockISomething3(ctrl *gomock.Controller) *MockISomething3 {
	mock := &MockISomething3{ctrl: ctrl}
	mock.recorder = &MockISomething3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockISomething3) EXPECT() *MockISomething3MockRecorder {
	return m.recorder
}

// GetName mocks base method.
func (m *MockISomething3) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockISomething3MockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockISomething3)(nil).GetName))
}
